### PR TITLE
make/targets/openshift/yaml-patch: fix missing repository

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @sttts @soltysh

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by sttts** [comment]
/lgtm
/approve
/hold

worth a proof PR ?

**Comment by s-urbaniak** [comment]
> worth a proof PR ?
indeed, i proofed it locally, let me open one against cert-manager-operator (the victim)

**Comment by s-urbaniak** [comment]
proof PR: https://github.com/openshift/api/pull/1083

**Pull request merged**
