### PR TITLE
Don't strip debugging symbols anymore

### PR DESCRIPTION
**Pull request by tnozicka**
Golang 1.15 reduced the overhead to ~10-15% which is now acceptable.

Requires https://github.com/openshift/release/pull/14049

/cc @smarterclayton @jim-minter

### CODE REVIEW

**Comment by tnozicka** [comment]
https://github.com/openshift/release/pull/14049 merged
/retest

**Comment by jim-minter** [comment]
@tnozicka I am +1 on enabling debug symbols.

**Comment by smarterclayton** [comment]
Strategically debug is now worth the overhead.

**Pull request merged**
