### PR TITLE
commitchecker: more updates

### PR DESCRIPTION
**Pull request by stevekuznetsov**
commitchecker: don't use an import alias

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

commitchecker: log what we're doing

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

commitchecker: use the ancestry-path

After we do our merge magic to reset the repo to the upstream state,
`git log` requires `--ancestry-path` to output meaningful data.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

commitchecker: ignore built binary

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 [MIRROR] libksba-1.5.1-6.el9_1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 161323 but expected size is: 161315
(27/182): pcre2-syntax-10.40-2.el9.noarch.rpm   343 kB/s | 147 kB     00:00    
(28/182): vim-minimal-8.2.2637-20.el9_1.x86_64. 1.0 MB/s | 678 kB     00:00    
[MIRROR] libksba-1.5.1-6.el9_1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 161323 but expected size is: 161315
[MIRROR] libksba-1.5.1-6.el9_1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 161323 but expected size is: 161315
[MIRROR] libksba-1.5.1-6.el9_1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 161323 but expected size is: 161315
[FAILED] libksba-1.5.1-6.el9_1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Error downloading packages:
  libksba-1.5.1-6.el9_1.x86_64: Cannot download, all mirrors were already tried without success 
```

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
